version: '3'

networks:
  macrosoft-api:

services:
  macrosoft-php:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    image: ppsdocker/macrosoft-php-sw
    container_name: MacrosoftPhp
    expose:
      - 9000
    networks:
      - macrosoft-api
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  macrosoft-web:
    image: library/nginx:1.20.1
    container_name: MacrosoftWeb
    ports:
      - "8086:80"
    networks:
      - macrosoft-api
    depends_on:
      - macrosoft-php
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build:
      context: .
      dockerfile: config/db/Dockerfile
    image: db
    platform: 'linux/x86_64'
    container_name: DB
    restart: unless-stopped
    volumes:
      - dev_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: databaza
      MYSQL_USER: dukes
      MYSQL_PASSWORD: dukes
      MYSQL_ROOT_PASSWORD: dukes
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --skip-innodb-file-per-table --server-id=1 --lower_case_table_names=1
    networks:
      - macrosoft-api

volumes:
  dev_db:
    driver: local